### ISSUE TITLE
Crashing when rotating image.

### ISSUE THREAD

**Issue by Epictek** [phillipberndt/pqiv#130]
Distro: Void Linux
Tried with the binary included in the repo, my own built binary and the nightly build.
```
(gdb) run *
Starting program: /usr/bin/pqiv *
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffeda03700 (LWP 8197)]
[New Thread 0x7fffed202700 (LWP 8198)]
(pqiv:8193): Gdk-ERROR **: 01:46:29.768: The program 'pqiv' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 500 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Thread 1 "pqiv" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff5601d01 in ?? () from /usr/lib/libglib-2.0.so.0
```

**Comment by Epictek** [comment]
Update, I didn't realise the H and L keys were actually for rotating the image. I changed from bspwm to gnome and pqiv seems to work fine so it seems to be a problem inside of bspwm.

**Comment by phillipberndt** [comment]
Thanks for reporting this!

This looks like an error due to the communication between pqiv and bspwm where both battle about some property until pqiv eventually requests a negative value. That's me first guess, at least.

A stable reproducer would be great, or, if you can manage to produce one, a backtrace for the crash. In any case I'll need the versions of gtk, gdk, and bspwm used.

**Comment by Epictek** [comment]
bspwm-0.9.3 (Also tried with latest git)
gdk-pixbuf-2.36.12_1
gtk+3-3.22.30_1
gtk+-2.24.32_1

Not sure what you mean by stable reproducer sorry, I'll see what I can do about getting a more detailed backtrace.

**Comment by phillipberndt** [comment]
The only thing that comes to my mind is that `-c` disables window decorations, and that window decorations might throw off size requests by a few pixels.

Try running with lrace,

    ltrace -e gtk_window_resize ./pqiv foo

to see the resize requests. The arguments shown are window id, width, height and an invalid fourth argument. Maybe either height or width becomes negative or something like that?

**Comment by phillipberndt** [comment]
I just had the insight that one of the effects of `-c` is that window borders are removed. Are you running pqiv in a floating window? There have been issues in the past with WMs and window borders.

Check please if removing the following code fixes the issue for you:

	// Resize if this has not worked before, but accept a slight deviation (might be round-off error)
	if(main_window_width >= 0 && abs(main_window_width - new_window_width) + abs(main_window_height - new_window_height) > 1) {
		requested_main_window_width = new_window_width;
		requested_main_window_height = new_window_height;
		gtk_window_resize(main_window, new_window_width / screen_scale_factor, new_window_height / screen_scale_factor);
	}

That's lines 2052:2057 in `main_window_resize_callback` in the latest code.

**Comment by phillipberndt** [comment]
I just tried reproducing this with bspwm master without any luck. So I won't be able to help with this issue until someone who experiences this issue and at the same time manages to find out what's happening comes around. Sorry.

**Comment by phillipberndt** [comment]
I can't even reproduce this in a void Linux running in a Virtualbox..

Can you still reproduce the issue if you set the `export GDK_SYNCHRONIZE=1` environment variable as the error message suggests? If so, please try running pqiv in a gdb session, executing `b gdk_x_error` before running the program. When it stops, please do a `bt` and send the output.

**Comment by Epictek** [comment]
```
~/pqiv ❯❯❯ GDK_SYNCHRONIZE=1 gdb pqiv                                                           ✘ 130 master ◼
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pqiv...done.
(gdb) b gdk_x_error
Function "gdk_x_error" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (gdk_x_error) pending.
(gdb) run ~/wallpapers/
Starting program: /home/kieran/pqiv/pqiv ~/wallpapers/
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe29c6700 (LWP 7887)]
[New Thread 0x7fffe21c5700 (LWP 7888)]
(pqiv:7883): Gdk-ERROR **: 10:15:36.769: The program 'pqiv' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 472 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Thread 1 "pqiv" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff3043415 in ?? () from /usr/lib/libglib-2.0.so.0
```

**Comment by phillipberndt** [comment]
At this point please type `bt` to generate a full backtrace.

**Comment by Epictek** [comment]
```
(gdb) bt
#0  0x00007ffff3043415 in  () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff3045d8c in g_log_writer_default () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff3044077 in g_log_structured_array () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff3044aae in g_log_structured_standard () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff6fe036b in  () at /usr/lib/libgdk-3.so.0
#5  0x00007ffff6fed0c3 in  () at /usr/lib/libgdk-3.so.0
#6  0x00007ffff628752a in _XError () at /usr/lib/libX11.so.6
#7  0x00007ffff6284487 in  () at /usr/lib/libX11.so.6
#8  0x00007ffff628452d in  () at /usr/lib/libX11.so.6
#9  0x00007ffff6285460 in _XReply () at /usr/lib/libX11.so.6
#10 0x00007ffff6280dad in XSync () at /usr/lib/libX11.so.6
#11 0x00007ffff6280e4b in  () at /usr/lib/libX11.so.6
#12 0x00007ffff6263f50 in XCreatePixmap () at /usr/lib/libX11.so.6
#13 0x0000000000413db3 in window_prerender_background_pixmap (window_width=485, window_height=864, scale_level=0.1758957654723127, fullscreen=0) at /home/kieran/pqiv/pqiv.c:4886
#14 0x00000000004157e3 in main_window_adjust_for_image () at /home/kieran/pqiv/pqiv.c:2190
#15 0x0000000000415da6 in transform_current_image (transformation=transformation@entry=0x7fffffffe0d0)
    at /home/kieran/pqiv/pqiv.c:3414
#16 0x000000000041a2d3 in action (action_id=ACTION_ROTATE_LEFT, parameter=...)
    at /home/kieran/pqiv/pqiv.c:5676
#17 0x000000000041b13a in queue_action_callback (user_data=<optimized out>) at /home/kieran/pqiv/pqiv.c:5449
#18 0x00007ffff303d508 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#19 0x00007ffff303d8f8 in  () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff303dbf2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff76d7f75 in gtk_main () at /usr/lib/libgtk-3.so.0
#22 0x000000000040af04 in main (argc=<optimized out>, argv=<optimized out>) at /home/kieran/pqiv/pqiv.c:8041
```
apologies forgot that last command :)

**Comment by Epictek** [comment]
I'm using an nvidia gpu if that's relevant at all?

**Comment by Epictek** [comment]
Works great! Thanks for the fix :)
